package com.study.springbootmybatis.entity;

import java.math.BigDecimal;
import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.key_word
     *
     * @mbggenerated
     */
    private String keyWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.punch_time
     *
     * @mbggenerated
     */
    private Date punchTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.salary_money
     *
     * @mbggenerated
     */
    private BigDecimal salaryMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.bonus_money
     *
     * @mbggenerated
     */
    private Double bonusMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.age
     *
     * @mbggenerated
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.sys_org_code
     *
     * @mbggenerated
     */
    private String sysOrgCode;

    public UserInfo(String id, String name, String keyWord, Date punchTime, BigDecimal salaryMoney, Double bonusMoney, String sex, Integer age, Date birthday, String email, String content, String createBy, Date createTime, String updateBy, Date updateTime, String sysOrgCode) {
        this.id = id;
        this.name = name;
        this.keyWord = keyWord;
        this.punchTime = punchTime;
        this.salaryMoney = salaryMoney;
        this.bonusMoney = bonusMoney;
        this.sex = sex;
        this.age = age;
        this.birthday = birthday;
        this.email = email;
        this.content = content;
        this.createBy = createBy;
        this.createTime = createTime;
        this.updateBy = updateBy;
        this.updateTime = updateTime;
        this.sysOrgCode = sysOrgCode;
    }

    public UserInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.id
     *
     * @return the value of demo.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.id
     *
     * @param id the value for demo.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.name
     *
     * @return the value of demo.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.name
     *
     * @param name the value for demo.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.key_word
     *
     * @return the value of demo.key_word
     *
     * @mbggenerated
     */
    public String getKeyWord() {
        return keyWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.key_word
     *
     * @param keyWord the value for demo.key_word
     *
     * @mbggenerated
     */
    public void setKeyWord(String keyWord) {
        this.keyWord = keyWord == null ? null : keyWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.punch_time
     *
     * @return the value of demo.punch_time
     *
     * @mbggenerated
     */
    public Date getPunchTime() {
        return punchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.punch_time
     *
     * @param punchTime the value for demo.punch_time
     *
     * @mbggenerated
     */
    public void setPunchTime(Date punchTime) {
        this.punchTime = punchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.salary_money
     *
     * @return the value of demo.salary_money
     *
     * @mbggenerated
     */
    public BigDecimal getSalaryMoney() {
        return salaryMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.salary_money
     *
     * @param salaryMoney the value for demo.salary_money
     *
     * @mbggenerated
     */
    public void setSalaryMoney(BigDecimal salaryMoney) {
        this.salaryMoney = salaryMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.bonus_money
     *
     * @return the value of demo.bonus_money
     *
     * @mbggenerated
     */
    public Double getBonusMoney() {
        return bonusMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.bonus_money
     *
     * @param bonusMoney the value for demo.bonus_money
     *
     * @mbggenerated
     */
    public void setBonusMoney(Double bonusMoney) {
        this.bonusMoney = bonusMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.sex
     *
     * @return the value of demo.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.sex
     *
     * @param sex the value for demo.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.age
     *
     * @return the value of demo.age
     *
     * @mbggenerated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.age
     *
     * @param age the value for demo.age
     *
     * @mbggenerated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.birthday
     *
     * @return the value of demo.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.birthday
     *
     * @param birthday the value for demo.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.email
     *
     * @return the value of demo.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.email
     *
     * @param email the value for demo.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.content
     *
     * @return the value of demo.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.content
     *
     * @param content the value for demo.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.create_by
     *
     * @return the value of demo.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.create_by
     *
     * @param createBy the value for demo.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.create_time
     *
     * @return the value of demo.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.create_time
     *
     * @param createTime the value for demo.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.update_by
     *
     * @return the value of demo.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.update_by
     *
     * @param updateBy the value for demo.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.update_time
     *
     * @return the value of demo.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.update_time
     *
     * @param updateTime the value for demo.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.sys_org_code
     *
     * @return the value of demo.sys_org_code
     *
     * @mbggenerated
     */
    public String getSysOrgCode() {
        return sysOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.sys_org_code
     *
     * @param sysOrgCode the value for demo.sys_org_code
     *
     * @mbggenerated
     */
    public void setSysOrgCode(String sysOrgCode) {
        this.sysOrgCode = sysOrgCode == null ? null : sysOrgCode.trim();
    }
}